[2025-04-08 09:24:07,885] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105278
[2025-04-08 09:24:08,035] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:24:08,153] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:24:08,269] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:24:08,274] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:24:08,669] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:24:08: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:24:08,687] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:24:08,786] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:27:45,338] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105274
[2025-04-08 09:27:45,547] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:27:45,615] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:27:45,771] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:27:45,778] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:27:46,271] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:27:46: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:27:46,303] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:27:46,455] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:27:48,506] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105274
[2025-04-08 09:27:48,654] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:27:48,669] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:27:48,778] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:27:48,785] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:27:49,042] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:27:49: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:27:49,059] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:27:49,150] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:28:04,895] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105278
[2025-04-08 09:28:05,049] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:28:05,065] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:28:05,183] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:28:05,190] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:28:05,425] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:28:05: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:28:05,448] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:28:05,555] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:28:07,978] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105278
[2025-04-08 09:28:08,124] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:28:08,128] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:28:08,229] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:28:08,235] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:28:08,446] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:28:08: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:28:08,463] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:28:08,627] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:28:29,923] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105274
[2025-04-08 09:28:30,035] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:28:30,050] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:28:30,145] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:28:30,154] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:28:30,447] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:28:30: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:28:30,463] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:28:30,595] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:28:33,157] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105274
[2025-04-08 09:28:33,299] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:28:33,310] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:28:33,392] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:28:33,399] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:28:33,614] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:28:33: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:28:33,646] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:28:33,775] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:29:06,928] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105278
[2025-04-08 09:29:07,087] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:29:07,097] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:29:07,214] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:29:07,223] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:29:07,519] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:29:07: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:29:07,533] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:29:07,659] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:29:09,264] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105278
[2025-04-08 09:29:09,402] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:29:09,416] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:29:09,505] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:29:09,518] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:29:09,759] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:29:09: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:29:09,775] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:29:09,892] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:32:08,273] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105305
[2025-04-08 09:32:08,436] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:32:08,567] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:32:08,851] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:32:08,933] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:32:09,219] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:32:09: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:32:09,234] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:32:09,387] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:33:39,055] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105300
[2025-04-08 09:33:39,204] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:33:39,220] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:33:39,593] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:33:39,717] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:33:40,200] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:33:40: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:33:40,217] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:33:40,486] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:35:23,121] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105316
[2025-04-08 09:35:23,298] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:35:23,335] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:35:23,469] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:35:23,477] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:35:23,835] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:35:23: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:35:23,851] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:35:24,043] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:39:41,452] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/src/modelfiles/PersonInfo.xlsx HTTP/1.1" 404 1815
[2025-04-08 09:39:41,542] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:39:43,580] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:39:43,597] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:39:43,597] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:39:43,601] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:39:43,619] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:39:43,675] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:40:34,833] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105324
[2025-04-08 09:40:34,975] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:40:34,989] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:40:35,124] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:40:35,131] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:40:35,387] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:40:35: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:40:35,411] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:40:35,488] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:40:39,552] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/src/modelfiles/DDMS_TestDeviceList.zip HTTP/1.1" 200 74514857
[2025-04-08 09:41:19,191] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105324
[2025-04-08 09:41:19,357] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:41:19,369] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:41:19,483] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:41:19,489] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:41:19,826] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:41:19: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:41:19,844] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:41:19,944] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:41:28,399] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105324
[2025-04-08 09:41:28,523] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:41:28,551] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:41:28,637] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:41:28,641] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:41:28,862] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:41:28: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:41:28,879] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:41:28,962] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:41:31,519] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:41:31,530] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:41:31,531] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:41:31,675] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:41:36,815] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105324
[2025-04-08 09:41:36,905] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:41:36,915] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:41:36,963] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:41:36,965] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:41:37,080] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:41:37: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:41:37,091] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:41:37,119] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:47:42,240] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 09:47:42,392] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:47:42,474] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:47:42,771] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:47:42,783] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:47:43,125] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:47:43: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:47:43,152] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:47:43,322] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:47:45,774] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 09:47:45,921] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:47:45,938] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:47:46,124] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:47:46,188] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:47:46,437] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:47:46: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:47:46,451] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:47:46,533] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:48:43,641] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 141, in TestDeviceListLNV
    mock_datalist = DeviceLNV.objects.all()
NameError: name 'DeviceLNV' is not defined
[2025-04-08 09:48:43,653] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 09:48:43,655] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 89490
[2025-04-08 09:48:53,237] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 09:48:53,350] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 09:48:53,358] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 09:48:53,426] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 09:48:53,432] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 09:48:53,686] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 09:48:53: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 09:48:53,719] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 09:48:53,794] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 09:48:55,151] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 141, in TestDeviceListLNV
    mock_datalist = DeviceLNV.objects.all()
NameError: name 'DeviceLNV' is not defined
[2025-04-08 09:48:55,155] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 09:48:55,159] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 89466
[2025-04-08 13:39:50,621] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /DeviceLNV/BorrowedDeviceLNV/ HTTP/1.1" 200 75404
[2025-04-08 13:39:50,794] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:39:50,863] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:39:51,020] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:39:51,030] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:39:51,304] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:39:53,023] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 13:39:53: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/DeviceLNV/BorrowedDeviceLNV/'>
[2025-04-08 13:39:53,052] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /DeviceLNV/BorrowedDeviceLNV/ HTTP/1.1" 200 2145488
[2025-04-08 13:39:53,660] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /media/DeviceLNV/Device/1513.jpg HTTP/1.1" 200 215360
[2025-04-08 13:39:53,673] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /media/DeviceLNV/Device/2156.jpg HTTP/1.1" 200 201323
[2025-04-08 13:39:53,679] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/244.jpg
[2025-04-08 13:39:53,687] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/244.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,694] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2260.jpg
[2025-04-08 13:39:53,699] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2260.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,709] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2214.jpg
[2025-04-08 13:39:53,719] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2214.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,722] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/233.jpg
[2025-04-08 13:39:53,733] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/233.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,734] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1462.jpg
[2025-04-08 13:39:53,740] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1462.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,758] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/253.jpg
[2025-04-08 13:39:53,767] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2218.jpg
[2025-04-08 13:39:53,772] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/253.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,772] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2218.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,774] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/261.jpg
[2025-04-08 13:39:53,786] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/261.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,788] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/262.jpg
[2025-04-08 13:39:53,804] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/268.jpg
[2025-04-08 13:39:53,807] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/262.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,816] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/268.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,822] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/266.jpg
[2025-04-08 13:39:53,837] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/266.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,846] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/269.jpg
[2025-04-08 13:39:53,855] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/267.jpg
[2025-04-08 13:39:53,857] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/269.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,865] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/267.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,872] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2098.jpg
[2025-04-08 13:39:53,888] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2098.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,895] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1292.jpg
[2025-04-08 13:39:53,905] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1292.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:53,907] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/209.jpg
[2025-04-08 13:39:53,922] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/209.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,927] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/264.jpg
[2025-04-08 13:39:53,938] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/264.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,943] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/228.jpg
[2025-04-08 13:39:53,956] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/228.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,963] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/214.jpg
[2025-04-08 13:39:53,977] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/214.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:53,983] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2049.jpg
[2025-04-08 13:39:53,989] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2049.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,026] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2050.jpg
[2025-04-08 13:39:54,033] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2050.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,036] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1301.jpg
[2025-04-08 13:39:54,051] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1301.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,054] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1298.jpg
[2025-04-08 13:39:54,063] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1298.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,064] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/259.jpg
[2025-04-08 13:39:54,077] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/259.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,078] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1383.jpg
[2025-04-08 13:39:54,093] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/260.jpg
[2025-04-08 13:39:54,096] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1383.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,109] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/260.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,132] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1294.jpg
[2025-04-08 13:39:54,137] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1296.jpg
[2025-04-08 13:39:54,140] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1294.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,141] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1296.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,148] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1297.jpg
[2025-04-08 13:39:54,157] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1302.jpg
[2025-04-08 13:39:54,157] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1297.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,170] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1302.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,176] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/223.jpg
[2025-04-08 13:39:54,186] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/223.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,192] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1934.jpg
[2025-04-08 13:39:54,201] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2220.jpg
[2025-04-08 13:39:54,203] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1934.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,210] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2220.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,211] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1460.jpg
[2025-04-08 13:39:54,223] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1460.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,237] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/242.jpg
[2025-04-08 13:39:54,247] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/242.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,248] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/246.jpg
[2025-04-08 13:39:54,258] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/246.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,260] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/248.jpg
[2025-04-08 13:39:54,276] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/248.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,278] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/252.jpg
[2025-04-08 13:39:54,288] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/243.jpg
[2025-04-08 13:39:54,290] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/252.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,296] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/243.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,310] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/251.jpg
[2025-04-08 13:39:54,320] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/250.jpg
[2025-04-08 13:39:54,323] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/251.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,328] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/250.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,332] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/254.jpg
[2025-04-08 13:39:54,341] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/254.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,360] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/334.jpg
[2025-04-08 13:39:54,369] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/334.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,377] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1065.jpg
[2025-04-08 13:39:54,385] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1065.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,392] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/316.jpg
[2025-04-08 13:39:54,404] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/316.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,404] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1046.jpg
[2025-04-08 13:39:54,416] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/331.jpg
[2025-04-08 13:39:54,417] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1046.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,426] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/331.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,437] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1492.jpg
[2025-04-08 13:39:54,456] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1492.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,464] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/317.jpg
[2025-04-08 13:39:54,469] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/317.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,474] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/344.jpg
[2025-04-08 13:39:54,485] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/319.jpg
[2025-04-08 13:39:54,485] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/344.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,489] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/319.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,494] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/322.jpg
[2025-04-08 13:39:54,503] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1066.jpg
[2025-04-08 13:39:54,505] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/322.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,517] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1066.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,525] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/345.jpg
[2025-04-08 13:39:54,530] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/345.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,543] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/341.jpg
[2025-04-08 13:39:54,553] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/341.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,567] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/337.jpg
[2025-04-08 13:39:54,572] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/337.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,578] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/332.jpg
[2025-04-08 13:39:54,584] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1178.jpg
[2025-04-08 13:39:54,585] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/332.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,586] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/326.jpg
[2025-04-08 13:39:54,593] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1178.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,601] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/327.jpg
[2025-04-08 13:39:54,602] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/326.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,607] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/327.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,625] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/324.jpg
[2025-04-08 13:39:54,634] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/324.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,639] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1179.jpg
[2025-04-08 13:39:54,658] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1179.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,660] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/321.jpg
[2025-04-08 13:39:54,670] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/321.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,673] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/283.jpg
[2025-04-08 13:39:54,679] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/283.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,693] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/292.jpg
[2025-04-08 13:39:54,695] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/294.jpg
[2025-04-08 13:39:54,697] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/292.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,709] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/294.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,721] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/286.jpg
[2025-04-08 13:39:54,736] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/286.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,736] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1550.jpg
[2025-04-08 13:39:54,744] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1550.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,746] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1551.jpg
[2025-04-08 13:39:54,763] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1551.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,765] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/375.jpg
[2025-04-08 13:39:54,778] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/375.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,790] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1553.jpg
[2025-04-08 13:39:54,795] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1553.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,798] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/374.jpg
[2025-04-08 13:39:54,807] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/281.jpg
[2025-04-08 13:39:54,810] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/374.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,812] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/281.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,822] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/289.jpg
[2025-04-08 13:39:54,831] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/289.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,843] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/373.jpg
[2025-04-08 13:39:54,849] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1044.jpg
[2025-04-08 13:39:54,856] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/373.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,858] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1044.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,865] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1512.jpg
[2025-04-08 13:39:54,878] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1512.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,889] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2047.jpg
[2025-04-08 13:39:54,901] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2047.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,902] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1461.jpg
[2025-04-08 13:39:54,910] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/338.jpg
[2025-04-08 13:39:54,911] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1461.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,914] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/338.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,928] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/340.jpg
[2025-04-08 13:39:54,934] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/339.jpg
[2025-04-08 13:39:54,941] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/340.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,941] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1552.jpg
[2025-04-08 13:39:54,953] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/339.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:54,954] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1552.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:54,973] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/282.jpg
[2025-04-08 13:39:54,987] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/282.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,005] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/304.jpg
[2025-04-08 13:39:55,009] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/307.jpg
[2025-04-08 13:39:55,018] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/370.jpg
[2025-04-08 13:39:55,019] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/304.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,026] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/307.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,027] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/299.jpg
[2025-04-08 13:39:55,032] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/370.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,039] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/299.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,043] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/290.jpg
[2025-04-08 13:39:55,059] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/291.jpg
[2025-04-08 13:39:55,060] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/290.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,065] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/291.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,108] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/305.jpg
[2025-04-08 13:39:55,116] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/296.jpg
[2025-04-08 13:39:55,123] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/305.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,123] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/296.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,138] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1177.jpg
[2025-04-08 13:39:55,142] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/288.jpg
[2025-04-08 13:39:55,144] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1177.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:55,153] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2128.jpg
[2025-04-08 13:39:55,157] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/288.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,161] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2128.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:55,166] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2129.jpg
[2025-04-08 13:39:55,172] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2129.jpg HTTP/1.1" 404 1803
[2025-04-08 13:39:55,175] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/295.jpg
[2025-04-08 13:39:55,176] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/295.jpg HTTP/1.1" 404 1800
[2025-04-08 13:39:55,183] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/287.jpg
[2025-04-08 13:39:55,184] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/287.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:04,845] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:45:04,845] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:45:04,849] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:45:04,849] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:45:04,901] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:45:04,913] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:45:22,177] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2025-04-08 13:45:22,206] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4823
[2025-04-08 13:45:22,277] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:45:22,319] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2025-04-08 13:45:22,333] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4823
[2025-04-08 13:45:24,328] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 13:45:24,362] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2025-04-08 13:45:24,402] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 302 0
[2025-04-08 13:45:25,378] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /DeviceLNV/BorrowedDeviceLNV/ HTTP/1.1" 200 75404
[2025-04-08 13:45:25,489] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:45:25,519] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:45:25,661] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:45:25,668] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:45:25,888] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:45:27,501] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 13:45:27: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/DeviceLNV/BorrowedDeviceLNV/'>
[2025-04-08 13:45:27,543] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /DeviceLNV/BorrowedDeviceLNV/ HTTP/1.1" 200 2145488
[2025-04-08 13:45:28,030] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/233.jpg
[2025-04-08 13:45:28,038] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/233.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,041] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2214.jpg
[2025-04-08 13:45:28,047] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2214.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,048] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2260.jpg
[2025-04-08 13:45:28,051] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2260.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,061] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/244.jpg
[2025-04-08 13:45:28,068] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2218.jpg
[2025-04-08 13:45:28,068] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/244.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,070] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2218.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,072] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1462.jpg
[2025-04-08 13:45:28,082] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/253.jpg
[2025-04-08 13:45:28,082] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1462.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,094] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/261.jpg
[2025-04-08 13:45:28,097] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/253.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,098] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/261.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,103] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/262.jpg
[2025-04-08 13:45:28,117] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/262.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,129] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/268.jpg
[2025-04-08 13:45:28,141] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/268.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,151] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/266.jpg
[2025-04-08 13:45:28,159] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/266.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,161] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2098.jpg
[2025-04-08 13:45:28,170] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2098.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,174] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/267.jpg
[2025-04-08 13:45:28,183] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/269.jpg
[2025-04-08 13:45:28,183] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/267.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,196] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/269.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,196] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1292.jpg
[2025-04-08 13:45:28,209] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/209.jpg
[2025-04-08 13:45:28,210] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1292.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,221] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/264.jpg
[2025-04-08 13:45:28,221] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/209.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,229] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/264.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,243] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/228.jpg
[2025-04-08 13:45:28,250] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/228.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,250] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/214.jpg
[2025-04-08 13:45:28,270] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/214.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,275] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2049.jpg
[2025-04-08 13:45:28,286] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2049.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,308] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2050.jpg
[2025-04-08 13:45:28,309] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1301.jpg
[2025-04-08 13:45:28,316] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2050.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,317] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1301.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,321] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1298.jpg
[2025-04-08 13:45:28,328] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1298.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,340] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/259.jpg
[2025-04-08 13:45:28,347] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/260.jpg
[2025-04-08 13:45:28,358] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/259.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,359] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/260.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,367] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1383.jpg
[2025-04-08 13:45:28,385] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1383.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,385] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1294.jpg
[2025-04-08 13:45:28,395] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1294.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,399] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1296.jpg
[2025-04-08 13:45:28,407] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1297.jpg
[2025-04-08 13:45:28,410] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1296.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,412] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1297.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,418] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/223.jpg
[2025-04-08 13:45:28,431] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/223.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,435] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1302.jpg
[2025-04-08 13:45:28,439] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1934.jpg
[2025-04-08 13:45:28,448] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1302.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,457] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1934.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,466] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2220.jpg
[2025-04-08 13:45:28,471] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2220.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,481] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1460.jpg
[2025-04-08 13:45:28,490] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1460.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,502] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/246.jpg
[2025-04-08 13:45:28,511] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/246.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,511] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/242.jpg
[2025-04-08 13:45:28,517] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/248.jpg
[2025-04-08 13:45:28,522] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/242.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,524] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/248.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,530] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/251.jpg
[2025-04-08 13:45:28,540] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/251.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,541] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/252.jpg
[2025-04-08 13:45:28,556] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/252.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,584] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/243.jpg
[2025-04-08 13:45:28,593] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/243.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,596] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1065.jpg
[2025-04-08 13:45:28,601] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1065.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,601] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/250.jpg
[2025-04-08 13:45:28,620] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/254.jpg
[2025-04-08 13:45:28,627] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/334.jpg
[2025-04-08 13:45:28,629] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/254.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,630] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/250.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,632] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/316.jpg
[2025-04-08 13:45:28,633] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/334.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,645] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/316.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,667] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/331.jpg
[2025-04-08 13:45:28,677] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/331.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,678] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1046.jpg
[2025-04-08 13:45:28,687] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1046.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,690] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1492.jpg
[2025-04-08 13:45:28,700] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1492.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,708] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/344.jpg
[2025-04-08 13:45:28,713] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/317.jpg
[2025-04-08 13:45:28,719] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/344.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,725] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/319.jpg
[2025-04-08 13:45:28,725] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/317.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,729] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/319.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,752] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/322.jpg
[2025-04-08 13:45:28,765] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/322.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,772] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1066.jpg
[2025-04-08 13:45:28,776] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1066.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,785] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/345.jpg
[2025-04-08 13:45:28,799] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/345.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,804] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/341.jpg
[2025-04-08 13:45:28,816] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/341.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,817] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/332.jpg
[2025-04-08 13:45:28,830] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/332.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,830] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/337.jpg
[2025-04-08 13:45:28,851] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/337.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,879] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1178.jpg
[2025-04-08 13:45:28,883] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/326.jpg
[2025-04-08 13:45:28,887] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1178.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,894] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/326.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,898] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/327.jpg
[2025-04-08 13:45:28,909] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/327.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,909] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/324.jpg
[2025-04-08 13:45:28,920] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1179.jpg
[2025-04-08 13:45:28,920] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/324.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,927] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/321.jpg
[2025-04-08 13:45:28,927] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1179.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:28,946] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/321.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,962] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/283.jpg
[2025-04-08 13:45:28,968] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/292.jpg
[2025-04-08 13:45:28,979] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/294.jpg
[2025-04-08 13:45:28,980] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/283.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,982] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/292.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:28,985] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/294.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,003] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/286.jpg
[2025-04-08 13:45:29,020] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/286.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,022] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1551.jpg
[2025-04-08 13:45:29,026] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1550.jpg
[2025-04-08 13:45:29,028] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1551.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,035] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1550.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,049] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/375.jpg
[2025-04-08 13:45:29,055] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/375.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,081] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/374.jpg
[2025-04-08 13:45:29,093] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/374.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,096] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1553.jpg
[2025-04-08 13:45:29,099] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/281.jpg
[2025-04-08 13:45:29,105] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1553.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,105] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1044.jpg
[2025-04-08 13:45:29,109] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/281.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,115] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/289.jpg
[2025-04-08 13:45:29,119] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1044.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,124] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/289.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,132] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/373.jpg
[2025-04-08 13:45:29,149] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/373.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,170] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1512.jpg
[2025-04-08 13:45:29,178] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1461.jpg
[2025-04-08 13:45:29,180] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1512.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,182] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1461.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,198] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2047.jpg
[2025-04-08 13:45:29,210] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/339.jpg
[2025-04-08 13:45:29,210] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2047.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,213] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/339.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,216] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/338.jpg
[2025-04-08 13:45:29,226] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/340.jpg
[2025-04-08 13:45:29,228] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/338.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,239] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/340.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,253] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1552.jpg
[2025-04-08 13:45:29,262] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/282.jpg
[2025-04-08 13:45:29,262] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1552.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,269] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/282.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,280] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/307.jpg
[2025-04-08 13:45:29,287] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/307.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,296] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/304.jpg
[2025-04-08 13:45:29,298] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/299.jpg
[2025-04-08 13:45:29,302] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/304.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,310] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/370.jpg
[2025-04-08 13:45:29,311] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/299.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,318] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/370.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,320] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/290.jpg
[2025-04-08 13:45:29,341] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/291.jpg
[2025-04-08 13:45:29,342] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/290.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,352] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/291.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,353] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/296.jpg
[2025-04-08 13:45:29,364] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/296.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,380] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/1177.jpg
[2025-04-08 13:45:29,389] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/1177.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,399] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/305.jpg
[2025-04-08 13:45:29,415] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/288.jpg
[2025-04-08 13:45:29,416] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/305.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,417] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/288.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,419] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2128.jpg
[2025-04-08 13:45:29,423] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2128.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,427] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/2129.jpg
[2025-04-08 13:45:29,428] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/2129.jpg HTTP/1.1" 404 1803
[2025-04-08 13:45:29,434] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/287.jpg
[2025-04-08 13:45:29,435] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/287.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:29,441] [log.py:228] [log:log_response] [WARNING]- Not Found: /media/DeviceLNV/Device/295.jpg
[2025-04-08 13:45:29,442] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /media/DeviceLNV/Device/295.jpg HTTP/1.1" 404 1800
[2025-04-08 13:45:30,030] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 13:45:30,163] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:45:30,169] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:45:30,316] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:45:30,365] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:45:30,549] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 13:45:30: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 13:45:30,565] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 13:45:30,649] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:45:38,030] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/src/modelfiles/DDMS_TestDeviceList.zip HTTP/1.1" 200 74517120
[2025-04-08 13:52:54,457] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 13:52:54,470] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-04-08 13:52:56,442] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 53164
[2025-04-08 13:52:56,917] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:53:02,488] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:53:03,291] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:53:04,102] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/app01/permission/ HTTP/1.1" 200 155560
[2025-04-08 13:53:04,150] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2025-04-08 13:53:06,619] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/app01/role/ HTTP/1.1" 200 77362
[2025-04-08 13:53:06,671] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2025-04-08 13:57:31,034] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 13:57:31,220] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:57:31,344] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:57:31,469] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:57:31,473] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:57:31,741] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 13:57:31: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 13:57:31,758] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 13:57:31,858] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:58:28,063] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 13:58:28,186] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 13:58:28,196] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 13:58:28,294] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 13:58:28,302] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 13:58:28,623] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 13:58:28: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 13:58:28,642] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 13:58:28,772] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 13:59:14,051] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 103, in TestDeviceListLNV
    print(onlineuser,UserInfo.objects.get(account=onlineuser))
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
app01.models.UserInfo.DoesNotExist: UserInfo matching query does not exist.
[2025-04-08 13:59:14,072] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 96877
[2025-04-08 13:59:14,296] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:00:35,075] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:00:35,166] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:00:35,179] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:00:35,258] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:00:35,263] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:00:35,534] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:00:35: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:00:35,538] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:00:35,548] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 14:02:45,403] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:02:45,561] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:02:45,575] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:02:45,743] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:02:45,759] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:02:46,188] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:02:46: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:02:46,226] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 14:02:46,248] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:03:40,394] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:03:40,503] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:03:40,516] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:03:40,608] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:03:40,613] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:03:40,892] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:03:40: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:03:40,909] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 2773
[2025-04-08 14:03:40,986] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:15:54,497] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:15:54,604] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:15:54,632] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:15:54,784] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:15:54,792] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:15:55,158] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:15:55,736] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:15:55: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:15:55,756] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 215807
[2025-04-08 14:39:21,135] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:39:21,279] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:39:21,370] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:39:21,583] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:39:21,647] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:39:22,148] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:39:22,406] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:39:22: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:39:22,427] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:39:58,591] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 457, in TestDeviceListLNV
    create_list.append(TestDeviceLNV(**i))
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'Customer' is an invalid keyword argument for this function
[2025-04-08 14:39:58,606] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:39:58,609] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 125471
[2025-04-08 14:42:02,316] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:42:02,433] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:42:02,463] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:42:02,641] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:42:02,698] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:42:03,125] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:42:03,299] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:42:03: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:42:03,318] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:42:15,763] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 308, in TestDeviceListLNV
    create_list.append(TestDeviceLNV(**i))
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'Customer' is an invalid keyword argument for this function
[2025-04-08 14:42:15,776] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:42:15,779] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 125471
[2025-04-08 14:44:25,871] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 221, in TestDeviceListLNV
    searchCategory = json.loads(responseData['searchCategory'])
  File "C:\Python372\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python372\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python372\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:44:25,885] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:44:25,905] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 118340
[2025-04-08 14:45:41,899] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:45:42,032] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:45:42,059] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:45:42,150] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:45:42,156] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:45:42,542] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:45:42,731] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:45:42: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:45:42,748] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:45:48,475] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 236, in TestDeviceListLNV
    for key, value in i.items():
AttributeError: 'str' object has no attribute 'items'
[2025-04-08 14:45:48,486] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:45:48,488] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 104576
[2025-04-08 14:47:30,794] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:47:30,890] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:47:30,905] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:47:30,974] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:47:30,978] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:47:31,348] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:47:31,933] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:47:31: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:47:31,956] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:47:39,512] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 310, in TestDeviceListLNV
    create_list.append(TestDeviceLNV(**i))
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'Customer' is an invalid keyword argument for this function
[2025-04-08 14:47:39,520] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:47:39,521] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 125812
[2025-04-08 14:50:01,291] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:50:01,423] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:50:01,470] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:50:01,534] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:50:01,538] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:50:01,891] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:50:02,459] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:50:02: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:50:02,479] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:50:09,254] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 311, in TestDeviceListLNV
    create_list.append(TestDeviceLNV(**i))
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'Customer' is an invalid keyword argument for this function
[2025-04-08 14:50:09,269] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:50:09,271] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 125811
[2025-04-08 14:53:01,462] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:53:01,586] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:53:01,622] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:53:01,712] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:53:01,719] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:53:02,075] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:53:02,293] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:53:02: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:53:02,326] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:53:12,718] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 312, in TestDeviceListLNV
    TestDeviceLNV.objects.bulk_create(create_list)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\query.py", line 465, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\query.py", line 1155, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-04-08 14:53:12,743] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 14:53:12,745] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 209761
[2025-04-08 14:57:35,196] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 14:57:35,305] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 14:57:35,320] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 14:57:35,399] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 14:57:35,402] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 14:57:35,719] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 14:57:35,890] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:57:35: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:57:35,905] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213360
[2025-04-08 14:57:43,850] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 14:57:43: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 14:57:43,860] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 213384
[2025-04-08 15:31:24,721] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:31:24,854] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:31:24,897] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:31:25,090] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:31:25,102] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:31:25,549] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:31:27,730] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 283, in TestDeviceListLNV
    value = getattr(i.field_name, field_name)
AttributeError: 'TestDeviceLNV' object has no attribute 'field_name'
[2025-04-08 15:31:27,746] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:31:27,749] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 96891
[2025-04-08 15:32:35,636] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:32:35,769] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:32:35,793] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:32:36,016] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:32:36,082] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:32:36,384] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:32:37,102] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 284, in TestDeviceListLNV
    value = getattr(i.field_name, field_name)
AttributeError: 'TestDeviceLNV' object has no attribute 'field_name'
[2025-04-08 15:32:37,106] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:32:37,108] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 96880
[2025-04-08 15:33:21,227] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:33:21,533] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:33:21,578] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:33:21,757] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:33:21,763] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:33:22,436] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:33:23,371] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 286, in TestDeviceListLNV
    if i.field_name:
AttributeError: 'TestDeviceLNV' object has no attribute 'field_name'
[2025-04-08 15:33:23,380] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:33:23,382] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 96990
[2025-04-08 15:34:14,693] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:34:14,814] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:34:14,821] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:34:14,937] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:34:14,940] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:34:15,323] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:34:16,046] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 329, in TestDeviceListLNV
    mock_dic[keyDev] = i.field_name
AttributeError: 'TestDeviceLNV' object has no attribute 'field_name'
[2025-04-08 15:34:16,051] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:34:16,053] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 98231
[2025-04-08 15:36:00,344] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:36:00,492] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:36:00,520] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:36:00,675] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:36:00,684] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:36:01,123] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:36:02,820] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 333, in TestDeviceListLNV
    mock_dic[keyStatus] = Status_dict[keyStatus]
KeyError: 'Status3'
[2025-04-08 15:36:02,833] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:36:02,837] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 98161
[2025-04-08 15:38:44,734] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:38:44,864] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:38:44,896] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:38:45,131] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:38:45,144] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:38:45,514] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:38:47,468] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestDeviceLNV/TestDeviceListLNV/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\DMS\TestDeviceLNV\views.py", line 335, in TestDeviceListLNV
    mock_dic[keyStatus] = Status_dict[keyStatus]
KeyError: 'Status3'
[2025-04-08 15:38:47,482] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-08 15:38:47,486] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 500 98084
[2025-04-08 15:40:16,613] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 15:40:16,727] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 15:40:16,743] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 15:40:16,935] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 15:40:16,991] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 15:40:17,283] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:40:18,973] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 15:40:18: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 15:40:18,990] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-08 15:45:52,655] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 53164
[2025-04-08 15:45:54,064] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/app01/role/ HTTP/1.1" 200 77362
[2025-04-08 15:45:54,112] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2025-04-08 15:45:54,324] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:45:57,918] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 15:45:58,748] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestDeviceLNV/testdevicelnv/ HTTP/1.1" 200 688376
[2025-04-08 15:45:58,804] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2025-04-08 16:28:29,360] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 16:28:29,469] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 16:28:29,546] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 16:28:29,613] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 16:28:29,613] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 16:28:29,880] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 16:28:32,135] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 16:28:32: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 16:28:32,169] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 982347
[2025-04-08 16:50:39,474] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 108116
[2025-04-08 16:50:39,643] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 16:50:39,690] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 16:50:39,862] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 16:50:39,906] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 16:50:40,407] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 16:50:49,457] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 16:50:49: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 16:50:49,483] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-08 16:57:38,315] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 107303
[2025-04-08 16:57:38,703] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 16:57:38,784] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 16:57:39,094] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 16:57:39,157] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 16:57:39,711] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 16:57:40,898] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 16:57:40: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 16:57:40,919] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-08 17:00:03,925] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 107320
[2025-04-08 17:00:04,097] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 17:00:04,136] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 17:00:04,421] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 17:00:04,503] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 17:00:04,915] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 17:00:06,721] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 17:00:06: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 17:00:06,742] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-08 17:03:04,639] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105346
[2025-04-08 17:03:04,912] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-08 17:03:05,069] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-08 17:03:05,493] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-08 17:03:05,638] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-08 17:03:06,550] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-08 17:03:09,621] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-08 17:03:09: C1010S3/edwin/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-08 17:03:09,673] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:25:06,598] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 302 0
[2025-04-09 10:25:06,636] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4823
[2025-04-09 10:25:07,305] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:25:07,353] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2025-04-09 10:25:07,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4823
[2025-04-09 10:25:15,866] [UserIP.py:90] [UserIP:process_response] [CRITICAL]- 系统错误Expecting value: line 1 column 1 (char 0)
[2025-04-09 10:25:15,912] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2025-04-09 10:25:15,965] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 302 0
[2025-04-09 10:25:17,385] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109746
[2025-04-09 10:25:17,529] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:25:17,603] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:25:17,791] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:25:17,838] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:25:18,312] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:25:22,960] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:25:22: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:25:22,980] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:27:12,041] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109734
[2025-04-09 10:27:12,189] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:27:12,213] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:27:12,425] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:27:12,497] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:27:12,953] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:27:14,336] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:27:14: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:27:14,347] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:28:40,984] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109735
[2025-04-09 10:28:41,149] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:28:41,177] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:28:41,330] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:28:41,331] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:28:41,779] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:28:44,886] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:28:44: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:28:44,910] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:36:07,176] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109835
[2025-04-09 10:36:07,355] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:36:07,369] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:36:07,485] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:36:07,491] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:36:07,870] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:36:09,668] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:36:09: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:36:09,686] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:52:33,418] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109735
[2025-04-09 10:52:33,589] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:52:33,684] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:52:33,907] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:52:33,955] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:52:34,443] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:52:35,842] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:52:35: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:52:35,887] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:53:06,809] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109735
[2025-04-09 10:53:06,924] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:53:06,946] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:53:07,063] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:53:07,103] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:53:07,406] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:53:13,037] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:53:13: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:53:13,053] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 10:55:23,088] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 109784
[2025-04-09 10:55:23,221] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 10:55:23,232] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 10:55:23,331] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 10:55:23,339] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 10:55:23,728] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 10:55:26,458] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 10:55:26: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 10:55:26,477] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 11:08:07,747] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 104760
[2025-04-09 11:08:07,872] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 11:08:08,019] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 11:08:08,287] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 11:08:08,352] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 11:08:08,846] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 11:08:12,765] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 11:08:12: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 11:08:12,777] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 11:10:59,099] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 104764
[2025-04-09 11:10:59,244] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 11:10:59,255] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 11:10:59,464] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 11:10:59,517] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 11:10:59,907] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 11:11:02,164] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 11:11:02: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 11:11:02,195] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 11:17:37,957] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 104830
[2025-04-09 11:17:38,062] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 11:17:38,122] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 11:17:38,290] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 11:17:38,332] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 11:17:38,700] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 11:17:40,444] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 11:17:40: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 11:17:40,459] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 11:18:38,467] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 104837
[2025-04-09 11:18:38,612] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 11:18:38,625] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 11:18:38,760] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 11:18:38,766] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 11:18:39,251] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 11:18:41,497] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 11:18:41: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 11:18:41,513] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 12:09:10,360] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105047
[2025-04-09 12:09:10,672] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 12:09:10,708] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 12:09:10,996] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 12:09:11,010] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 12:09:11,494] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 12:09:12,869] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 12:09:12: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 12:09:12,887] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
[2025-04-09 13:21:22,844] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 105065
[2025-04-09 13:21:23,201] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2025-04-09 13:21:23,239] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2025-04-09 13:21:23,476] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2025-04-09 13:21:23,539] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2025-04-09 13:21:24,066] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 35458
[2025-04-09 13:21:27,604] [UserIP.py:88] [UserIP:process_response] [INFO]- 2025-04-09 13:21:27: C1010S3/AnonymousUser/Cao.Edwin> None/EDWIN/bxbei > 127.0.0.1/127.0.0.1 > <WSGIRequest: POST '/TestDeviceLNV/TestDeviceListLNV/'>
[2025-04-09 13:21:27,617] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestDeviceLNV/TestDeviceListLNV/ HTTP/1.1" 200 979898
